select Title, rating from earning left join IMDB on earning.movie_id = IMDB.movie_id where domestic > 100000000 and metacritic > 60 and IMDB.title like '%2012%'
select Title, rating from earning left join IMDB on earning.movie_id = IMDB.movie_id where domestic > 100000000 and metacritic > 60 and IMDB.title like '%2012%'
select Title, rating from earning left join IMDB on earning.movie_id = IMDB.movie_id where domestic > 100000000 and metacritic > 60 and IMDB.title like '%2012%'
select Title, rating from earning left join IMDB on earning.movie_id = IMDB.movie_id where domestic > 100000000 and metacritic > 60 and IMDB.title like '%2012%'
select Title, rating from earning left join IMDB on earning.movie_id = IMDB.movie_id where domestic > 100000000 and metacritic > 60 and IMDB.title like '%2012%'
select Title, rating from earning left join IMDB on earning.movie_id = IMDB.movie_id where domestic > 100000000 and metacritic > 60 and IMDB.title like '%2012%'
select Title, rating from earning left join IMDB on earning.movie_id = IMDB.movie_id where domestic > 100000000 and metacritic > 60 and IMDB.title like '%2012%'
select Title, rating from earning left join IMDB on earning.movie_id = IMDB.movie_id where domestic > 100000000 and metacritic > 60 and IMDB.title like '%2012%'
